apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8skv-deployment
spec:
  replicas: 1  # Consider your scaling needs
  selector:
    matchLabels:
      app: k8skv
  template:
    metadata:
      labels:
        app: k8skv
    spec:
      containers:
      - name: k8skv
        image: richardhightower/k8skv:v0.3
        ports:
        - containerPort: 5001

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8skv-ingress
spec:
  ingressClassName: "nginx"
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: k8skv-server
                port:
                  number: 5001

---

apiVersion: v1
kind: Service
metadata:
  name: k8skv-server
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 5001
    targetPort: 5001
  selector:
    app: k8skv

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: configmap-reader
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-reader-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default  # Assuming you're using the default service account
  namespace: default
roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io

